find/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('find/', views.find, name="find"),
    path('generate/', views.generate, name="generate"),
    path('recipe/', views.recipe, name="recipe"),
    path('generateRecipe/', views.generateRecipe, name="generateRecipe"),
    path('ingredient/', views.findIngredient, name="ingredient"),
    path('ingredientRecipe/', views.ingredientRecipe, name="ingredientRecipe")
]

foodapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("find.urls")),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('create/', views.create, name='createProfile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('favorites_list/', views.favorites_list, name='favorites_list'),
    path('favorite/<int:id>', views.favorite, name="favorite"),
    path('delete_favorite/', views.delete_favorite, name='delete_favorite'), 
    path('save_favorite/', views.save_favorite, name="save_favorite"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    height = models.FloatField()
    weight = models.FloatField()
    diseases = models.JSONField(default=list, blank=True)
    allergies = models.JSONField(default=list, blank=True)
    favorites = models.JSONField(default=list, blank=True)

    def __str__(self):
        return "Profile of `" + self.user.first_name + "`"
    
class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    ingredients = models.TextField()
    steps = models.TextField()

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['age', 'height', 'weight']
        
        widgets = {
            'age': forms.TextInput(attrs={'class':"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"}), 
            'height': forms.TextInput(attrs={'class':"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"}), 
            'weight': forms.TextInput(attrs={'class':"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"}), 
        }

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from .models import Profile, Favorite
from .forms import ProfileForm
from django.contrib.auth.decorators import login_required
import json

# Create your views here.

@login_required
def profile(request):
    try:
        userProfile = Profile.objects.get(user=request.user)
        print(userProfile)
        return render(request, 'users/profile.html', {'profile': userProfile})
    except Profile.DoesNotExist:
        return redirect('users:createProfile')

def create(request): 
    if request.method == 'POST':
        print(request.POST)
        print(request.body)
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.diseases = [
                disease for disease in request.POST.getlist('diseases') if disease
            ]
            profile.allergies = [
                allergy for allergy in request.POST.getlist('allergies') if allergy
            ]
            # profile.favorites = [
            #     favorite for favorite in request.POST.getlist('favorites') if favorite
            # ]
            profile.save()
            return redirect('users:profile')
    else:
        form = ProfileForm()
        predefined_diseases = ["Diabetes", "Asthma", "Celiac Disease", "Hypertension"]  # Example
        predefined_allergies = ["Peanut", "Dairy", "Seafood", "Shellfish"]  # Example
        return render(request, 'users/profileform.html', {'form': form,
                                                  'predefined_diseases': predefined_diseases,
                                                  'predefined_allergies': predefined_allergies,})


@login_required
def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        print(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.diseases = request.POST.getlist('diseases')
            profile.allergies = request.POST.getlist('allergies')
            profile.save()
            return redirect('users:profile') 
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'users/edit_profile.html', {'form': form, 'profile': profile})
@login_required
def favorites_list(request):
    return render(request, 'users/favorite_list.html')

@login_required
def favorite(request, id):
    item = Favorite.objects.get(id=id)
    return render(request, 'users/favorite.html', {"item": item})

@login_required
def save_favorite(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body.decode('utf-8'))
            print(data)
            entry = Favorite()
            entry.user = request.user
            entry.name = data.get('item')
            entry.ingredients = data.get('ingredients')
            entry.steps = data.get('steps')
            entry.save()
            return JsonResponse({'message': 'Recipe saved to favorites!'})

        except Profile.DoesNotExist:
            return JsonResponse({'message': 'Profile not found.'}, status=404)

    return JsonResponse({'message': 'Invalid request method.'}, status=405)



@login_required
def delete_favorite(request):
    if request.method == 'POST':
        favorite_id = request.GET.get('favorite_id')
        try:
            favorite = Favorite.objects.get(pk=favorite_id)
            favorite.delete()
            return JsonResponse({'success': True})
        except Favorite.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'favorite not found.'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method.'})

users/templates/users/edit_profile.html
{% extends 'base.html' %}
{% block body %}
{{ profile.diseases | json_script:"disease_data" }}
{{ profile.allergies | json_script:"allergies_data" }}
<div class="container mx-auto p-4">
    <h1 class="text-4xl font-bold text-center mb-8 text-[#000022]">Edit Your Profile</h1>
    
    <div class="bg-white rounded-lg shadow-md p-8">
        <form method="POST" class="bg-white rounded-lg shadow-md p-8">
            {% csrf_token %}

            <div class="mb-4">
                <label for="id_age" class="block text-gray-700 text-sm font-bold mb-2">Age:</label>
                <input type="number" id="id_age" name="age" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ form.age.value|default_if_none:'' }}" required>
            </div>

            <div class="mb-4">
                <label for="id_height" class="block text-gray-700 text-sm font-bold mb-2">Height (cm):</label>
                <input type="number" id="id_height" name="height" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ form.height.value|default_if_none:'' }}" required>
            </div>

            <div class="mb-4">
                <label for="id_weight" class="block text-gray-700 text-sm font-bold mb-2">Weight (kg):</label>
                <input type="number" id="id_weight" name="weight" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ form.weight.value|default_if_none:'' }}" required>
            </div>

            <div class="mb-4">
                <label for="id_diseases" class="block text-gray-700 text-sm font-bold mb-2">Diseases:</label>
                <div id="disease-tags" class="flex flex-wrap gap-2">
                    <div class="flex flex-col gap-2" id="predefined-diseases">
                        {% for disease in profile.diseases %}
                            <div class="flex items-center" id="disease-{{ disease }}">
                                <input type="checkbox" id="disease-{{ disease }}" name="diseases" value="{{ disease }}" class="mr-2" checked> 
                                <label for="disease-{{ disease }}" class="text-gray-700 text-sm">{{ disease }}</label>
                                <button type="button" onclick="deleteTag('disease-{{ disease }}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-col gap-2" id="custom-diseases"></div>
                </div>
                <input type="text" id="new-disease" placeholder="Add new disease" class="border rounded px-3 py-2">
                <button type="button" onclick="addDiseaseTag()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded">Add</button>
                
            </div>
           
            <div class="mb-4">
                <label for="id_allergies" class="block text-gray-700 text-sm font-bold mb-2">Allergies:</label>
                <div id="allergy-tags" class="flex flex-wrap gap-2">
                    <div class="flex flex-col gap-2" id="predefined-allergies">
                        {% for allergy in profile.allergies %}
                            <div class="flex items-center" id="allergy-{{ allergy }}">
                                <input type="checkbox" id="allergy-{{ allergy }}" name="allergies" value="{{ allergy }}" class="mr-2" checked>
                                <label for="allergy-{{ allergy }}" class="text-gray-700 text-sm">{{ allergy }}</label>
                                <button type="button" onclick="deleteTag('allergy-{{ allergy }}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-col gap-2" id="custom-allergies"></div>
                </div>
                <input type="text" id="new-allergy" placeholder="Add new allergy" class="border rounded px-3 py-2">
                <button type="button" onclick="addAllergyTag()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded">Add</button>
            </div>

            <!--
            <div class="mb-4">
                <label for="id_favorites" class="block text-gray-700 text-sm font-bold mb-2">Favorites:</label>
                <div id="favorite-tags" class="flex flex-wrap gap-2">
                    <div class="flex flex-wrap gap-2" id="predefined-favorites">
                        {% for favorite in profile.favorites %}
                            <div class="flex items-center" id="favorite-{{ favorite }}">
                                <input id="favorite-{{ favorite }}" type="checkbox" class="mr-2" name="favorites" checked>
                                <label for="favorite-{{ favorite }}" class="text-gray-700 text-sm">{{ favorite }}</label>
                                <button type="button" onclick="deleteTag('favorite-{{ favorite }}')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-wrap gap-2" id="custom-favorites"></div>
                </div>
                <input type="text" id="new-favorite" placeholder="Add new favorite" class="border rounded px-3 py-2">
                <button type="button" onclick="addFavoriteTag()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Add</button>
            </div>
            -->

            <button type="submit" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded">Save Changes</button> 
        </form>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    console.log(document.getElementById('disease_data').textContent)
    const customDiseasesDiv = document.getElementById("predefined-diseases");
    function addDiseaseTag() {
        const newDisease = document.getElementById("new-disease").value.trim();
        if (newDisease !== "") {
            const diseaseTags = document.getElementById("disease-tags");
            const newDiseaseElement = document.createElement("div");
            newDiseaseElement.classList.add("flex", "items-center");
            newDiseaseElement.setAttribute('id', `disease-${newDisease}`);
            newDiseaseElement.innerHTML = `
                <input type="checkbox" id="disease-${newDisease}" name="diseases" value="${newDisease}" class="mr-2" checked>
                <label for="disease-${newDisease}" class="text-gray-700 text-sm">${newDisease}</label>
                <button type="button" onclick="deleteTag('disease-${newDisease}')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
            `;
            customDiseasesDiv.appendChild(newDiseaseElement);
            document.getElementById("new-disease").value = "";
        }
    }


    // Allergies
    const customAllergyDiv = document.getElementById("predefined-allergies");
    function addAllergyTag() {
        const newAllergy = document.getElementById("new-allergy").value.trim();
        if (newAllergy !== "") {
            const newAllergyElement = document.createElement("div");
            newAllergyElement.classList.add("flex", "items-center");
            newAllergyElement.setAttribute('id', `allergy-${newAllergy}`);
            newAllergyElement.innerHTML = `
                <input type="checkbox" id="allergy-${newAllergy}" name="allergies" value="${newAllergy}" class="mr-2" checked>
                <label for="allergy-${newAllergy}" class="text-gray-700 text-sm">${newAllergy}</label>
                <button type="button" onclick="deleteTag('allergy-${newAllergy}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
            `;
            customAllergyDiv.appendChild(newAllergyElement);
            document.getElementById("new-allergy").value = "";
        }
    }


    /*
    // Favorites
    const customFavoriteDiv = document.getElementById("custom-favorites");
    function addFavoriteTag() {
        const newFavorite = document.getElementById("new-favorite").value.trim();
        if (newFavorite !== "") {
            const newFavoriteElement = document.createElement("div");
            newFavoriteElement.classList.add("flex", "items-center");
            newFavoriteElement.setAttribute('id', `favorite-${newFavorite}`);
            newFavoriteElement.innerHTML = `
                <input type="checkbox" id="favorite-${newFavorite}" name="favorites" value="${newFavorite}" class="mr-2">
                <label for="favorite-${newFavorite}" class="text-gray-700 text-sm">${newFavorite}</label>
                <button type="button" onclick="deleteTag('favorite-${newFavorite}')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
            `;
            customFavoriteDiv.appendChild(newFavoriteElement);
            document.getElementById("new-favorite").value = "";
        }
    }
        */


    // Generalized delete function for both diseases and allergies
    function deleteTag(tagId) {
        const tagElement = document.getElementById(tagId);
        if (tagElement) {
            tagElement.remove();
        }
    }

    $(document).ready(function() {
        $('form').on('submit', function(e) {
        });
        $('#new-disease').on('keypress', function(e) {
            if (e.which == 13) {
                addDiseaseTag();
                e.preventDefault(); // Prevent form submission
            }
        });
        $('#new-allergy').on('keypress', function(e) {
            if (e.which == 13) {
                addAllergyTag();
                e.preventDefault(); // Prevent form submission
            }
        });
    });
    
    
</script>
{% endblock script %}

users/templates/users/favorite.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto p-4 text-black">
    <div class="max-w-4xl mx-auto bg-white rounded-lg p-8 shadow-md">
        <h2 id="title" class="text-3xl font-bold mb-4 text-[#000022]">
            {{ item.name | safe }}
        </h2>

        <div class="mb-4">
            <h3 class="text-lg font-bold mb-2 text-[#000022]">Ingredients:</h3>
            <ul id="ingredients-list" class="list-disc list-inside text-[#000022]">
                {{item.ingredients|safe}}
                <!--
                {% for ingredient in item.ingredients.splitlines %}
                    <li>{{ ingredient }}</li>
                {% endfor %}
                -->
            </ul>
        </div>

        <div class="mb-4">
            <h3 class="text-lg font-bold mb-2 text-[#000022]">Steps:</h3>
            <div id="result" class="prose prose-lg text-[#000022]">
                {{ item.steps | safe }}
            </div>
        </div>
        <div class="flex justify-center"><a href="{% url "users:favorites_list"%}" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Back to list</a></div>
        
    </div>
</div>
{% endblock body %}

users/templates/users/favorite_list.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto p-4 text-black">
    <h1 class="text-4xl font-bold text-center mb-8 text-[#000022]">Your Favorite Recipes</h1>

    <div id="favorites-list" class="max-w-md mx-auto">
        {% if user.favorite_set.all %}
        {% for favorite in user.favorite_set.all %}
        <div class="bg-gray-100 rounded-lg p-4 shadow-md mb-4 flex items-center justify-between" id="favorite-{{ favorite.id }}">
            <div>
                <a href="{% url 'users:favorite' favorite.id %}">
                    <h2 class="text-2xl font-bold mb-2 text-[#000022]">{{ favorite.name | safe }}</h2>
                </a>
            </div>
            <div>
                <button data-favorite-id="{{ favorite.id }}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" onclick="deleteFavorite(this)">Delete</button>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="text-center mt-8">
            <p class="text-gray-600 text-lg">You don't have any saved recipes yet.</p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    async function deleteFavorite(button) {
        const favoriteId = button.dataset.favoriteId;
        const endpointURL = `{% url 'users:delete_favorite' %}?favorite_id=${favoriteId}`;
        if (confirm("Are you sure you want to delete this recipe? You can't revert this action.")) {
            try {
                const response = await fetch(endpointURL, {
                    method: 'POST',
                    headers: {
                        "Content-Type": "application/json",
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({ 'favorite_id': favoriteId })
                });
                if (response.ok) {
                    const favoriteElement = document.getElementById(`favorite-${favoriteId}`);
                    if (favoriteElement) {
                        favoriteElement.remove();
                    }
                    const favoritesList = document.getElementById('favorites-list');
                    if (favoritesList.children.length === 0) {
                        const emptyMessageDiv = document.createElement("div");
                        emptyMessageDiv.classList.add("text-center", "mt-8");
                        const emptyMessage = document.createElement("p");
                        emptyMessage.textContent = "You don't have any saved recipes yet.";
                        emptyMessage.classList.add("text-gray-600", "text-lg");
                        emptyMessageDiv.appendChild(emptyMessage);
                        favoritesList.appendChild(emptyMessageDiv);
                    }
                    console.log("Favorite deleted successfully!");
                } else {
                    console.error("Error deleting favorite:", response.status);
                }
            } catch (error) {
                console.error("Error occurred:", error);
            }
        }
    }
</script>
{% endblock script %}

users/templates/users/profileform.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto p-4">
    <h1 class="text-4xl font-bold text-center mb-8 text-[#000022]">Create Profile</h1>

    <div class="bg-white rounded-lg shadow-md p-8">
        <form method="POST" class="bg-white rounded-lg shadow-md p-8">
            {% csrf_token %}

            <div class="mb-4">
                <label for="id_age" class="block text-gray-700 text-sm font-bold mb-2">Age:</label>
                <input type="number" id="id_age" name="age" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ form.age.value|default_if_none:'' }}" required>
            </div>

            <div class="mb-4">
                <label for="id_height" class="block text-gray-700 text-sm font-bold mb-2">Height (cm):</label>
                <input type="number" id="id_height" name="height" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ form.height.value|default_if_none:'' }}" required>
            </div>

            <div class="mb-4">
                <label for="id_weight" class="block text-gray-700 text-sm font-bold mb-2">Weight (kg):</label>
                <input type="number" id="id_weight" name="weight" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{ form.weight.value|default_if_none:'' }}" required>
            </div>
            <div class="mb-4">
                <label for="id_diseases" class="block text-gray-700 text-sm font-bold mb-2">Diseases:</label>
                <div id="disease-tags" class="flex flex-wrap gap-2">
                    <div class="flex flex-col gap-2" id="predefined-diseases">
                        {% for disease in predefined_diseases %}
                            <div class="flex items-center" id="div-disease-{{ disease }}">
                                <input type="checkbox" id="disease-{{ disease }}" name="diseases" value="{{ disease }}" class="mr-2"> 
                                <label for="disease-{{ disease }}" class="text-gray-700 text-sm">{{ disease }}</label>
                                <button type="button" onclick="deleteTag('disease-{{ disease }}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-col gap-2" id="custom-diseases"></div>
                </div>
                <input type="text" id="new-disease" placeholder="Add new disease" class="border rounded px-3 py-2">
                <button type="button" onclick="addDiseaseTag()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded">Add</button>
                
            </div>
            
            <div class="mb-4">
                <label for="id_allergies" class="block text-gray-700 text-sm font-bold mb-2">Allergies:</label>
                <div id="allergy-tags" class="flex flex-wrap gap-2">
                    <div class="flex flex-col gap-2" id="predefined-allergies">
                        {% for allergy in predefined_allergies %}
                            <div class="flex items-center" id="div-allergy-{{ allergy }}">
                                <input type="checkbox" id="allergy-{{ allergy }}" name="allergies" value="{{ allergy }}" class="mr-2">
                                <label for="allergy-{{ allergy }}" class="text-gray-700 text-sm">{{ allergy }}</label>
                                <button type="button" onclick="deleteTag('allergy-{{ allergy }}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="flex flex-col gap-2" id="custom-allergies"></div>
                </div>
                <input type="text" id="new-allergy" placeholder="Add new allergy" class="border rounded px-3 py-2">
                <button type="button" onclick="addAllergyTag()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded">Add</button>
            </div>

            <button type="submit" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded">Save</button> 
        </form>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    const customDiseasesDiv = document.getElementById("custom-diseases");
    function addDiseaseTag() {
        const newDisease = document.getElementById("new-disease").value.trim();
        if (newDisease !== "") {
            const diseaseTags = document.getElementById("disease-tags");
            const newDiseaseElement = document.createElement("div");
            newDiseaseElement.classList.add("flex", "items-center");
            newDiseaseElement.setAttribute('id', `disease-${newDisease}`);
            newDiseaseElement.innerHTML = `
                <input type="checkbox" id="disease-${newDisease}" name="diseases" value="${newDisease}" class="mr-2" checked>
                <label for="disease-${newDisease}" class="text-gray-700 text-sm">${newDisease}</label>
                <button type="button" onclick="deleteTag('disease-${newDisease}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
            `;
            customDiseasesDiv.appendChild(newDiseaseElement);
            document.getElementById("new-disease").value = "";
        }
    }

    // Allergies
    const customAllergyDiv = document.getElementById("predefined-allergies");
    function addAllergyTag() {
        const newAllergy = document.getElementById("new-allergy").value.trim();
        if (newAllergy !== "") {
            const newAllergyElement = document.createElement("div");
            newAllergyElement.classList.add("flex", "items-center");
            newAllergyElement.setAttribute('id', `allergy-${newAllergy}`);
            newAllergyElement.innerHTML = `
                <input type="checkbox" id="allergy-${newAllergy}" name="allergies" value="${newAllergy}" class="mr-2" checked>
                <label for="allergy-${newAllergy}" class="text-gray-700 text-sm">${newAllergy}</label>
                <button type="button" onclick="deleteTag('allergy-${newAllergy}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
            `;
            customAllergyDiv.appendChild(newAllergyElement);
            document.getElementById("new-allergy").value = "";
        }
    }
    /*
    const customFavoriteDiv = document.getElementById("predefined-favorites");
    function addFavoriteTag() {
        const newFavorite = document.getElementById("new-favorite").value.trim();
        if (newFavorite !== "") {
            const newFavoriteElement = document.createElement("div");
            newFavoriteElement.classList.add("flex", "items-center");
            newFavoriteElement.setAttribute('id', `favorite-${newFavorite}`);
            newFavoriteElement.innerHTML = `
                <input type="checkbox" id="favorite-${newFavorite}" name="favorites" value="${newFavorite}" class="mr-2" checked>
                <label for="favorite-${newFavorite}" class="text-gray-700 text-sm">${newFavorite}</label>
                <button type="button" onclick="deleteTag('favorite-${newFavorite}')" class="bg-red-500 hover:bg-red-700 text-white text-xs py-1 px-2 rounded transition duration-300 ml-2">Delete</button>
            `;
            customFavoriteDiv.appendChild(newFavoriteElement);
            document.getElementById("new-favorite").value = "";
        }
    }
    */


    // Generalized delete function for both diseases and allergies
    function deleteTag(tagId) {
        const tagElement = document.getElementById(tagId);
        if (tagElement) {
            tagElement.remove();
        }
    }

    $(document).ready(function() {
        $('form').on('submit', function(e) {
            e.preventDefault();
            // Prevent default form submission behavior 
        });
        $('#new-disease').on('keypress', function(e) {
            if (e.which == 13) {
                addDiseaseTag();
                e.preventDefault(); // Prevent form submission
            }
        });
        $('#new-allergy').on('keypress', function(e) {
            if (e.which == 13) {
                addAllergyTag();
                e.preventDefault(); // Prevent form submission
            }
        });
    });
</script>
{% endblock script %}