find/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('find/', views.find, name="find"),
    path('generate/', views.generate, name="generate"),
    path('recipe/', views.recipe, name="recipe"),
    path('generateRecipe/', views.generateRecipe, name="generateRecipe"),
    path('ingredient/', views.findIngredient, name="ingredient"),
    path('ingredientRecipe/', views.ingredientRecipe, name="ingredientRecipe")
]

foodapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("find.urls")),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('create/', views.create, name='createProfile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('favorites_list/', views.favorites_list, name='favorites_list'),
    path('favorite/<int:id>', views.favorite, name="favorite"),
    path('delete_favorite/', views.delete_favorite, name='delete_favorite'), 
    path('save_favorite/', views.save_favorite, name="save_favorite"),
]

templates/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodSense</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
</head>
<body class="bg-[#fbf5f3] min-h-screen text-[#000022] font-sans"> 
    <header id="navbar" class="bg-opacity-75 backdrop-blur-sm fixed top-0 left-0 w-full z-10 transition duration-300 ease-in-out">
        <section class="max-w-4xl mx-auto p-4 flex justify-between items-center">
            <a href="{% url 'index' %}" class="hover:opacity-90 flex items-center">
                <img src="{% static 'images/logo-white.png' %}" alt="EDUQUEST Logo" class="h-10 mr-2"> 
                <h1 class="text-3xl font-medium">
                    Food Sense
                </h1>
            </a>
            <nav class="block space-x-6 text-lg " aria-label="main">
                {% if not user.is_authenticated %}
                    <a href="{% provider_login_url 'google' %}" class="hover:opacity-90">Sign In with Google</a>
                {% else %}
                    <a href="{% url 'users:favorites_list' %}" class="hover:opacity-90">Favorites</a>
                    <a href="{% url 'users:profile' %}" class="hover:opacity-90">Profile</a>
                    <a href="{% url 'account_logout' %}" class="hover:opacity-90">Sign Out</a>
                {% endif %}
            </nav>
        </section>
    </header>
    <main class="mt-20">
        {% block body %}
        {% endblock body %}
    </main>
    <script>
        const navbar = document.getElementById('navbar');
        let isNavbarVisible = true; 
        
        window.onscroll = function() {
            const currentScrollPos = window.pageYOffset;
        
            if (currentScrollPos > 0 && isNavbarVisible) { // Check if scrolled down and navbar is visible
                navbar.style.transform = 'translateY(-80px)'; // Shrink navbar
                isNavbarVisible = false;
            } else if (currentScrollPos === 0 && !isNavbarVisible) { // Check if at top and navbar is hidden
                navbar.style.transform = 'translateY(0)'; // Expand navbar
                isNavbarVisible = true;
            }
        };
    </script>
    {% block script %}
    <script>
    </script>
    {% endblock script %}
</body>
</html>