find/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('find/', views.find, name="find"),
    path('generate/', views.generate, name="generate"),
    path('recipe/', views.recipe, name="recipe"),
    path('generateRecipe/', views.generateRecipe, name="generateRecipe"),
    path('ingredient/', views.findIngredient, name="ingredient"),
    path('ingredientRecipe/', views.ingredientRecipe, name="ingredientRecipe")
]

foodapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("find.urls")),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('create/', views.create, name='createProfile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('favorites_list/', views.favorites_list, name='favorites_list'),
    path('favorite/<int:id>', views.favorite, name="favorite"),
    path('delete_favorite/', views.delete_favorite, name='delete_favorite'), 
    path('save_favorite/', views.save_favorite, name="save_favorite"),
]

find/models.py
from django.db import models

# Create your models here.

find/views.py
from .markdownRenderer import md_to_html
from django.shortcuts import render, redirect
from django.http import JsonResponse
import googlemaps
from gemini.functions import *
from django.contrib.auth.decorators import login_required
from foodapp.settings import GOOGLE_API_KEY, GOOGLE_AI_KEY
import requests
from users.models import Profile, Favorite
import json
import google.generativeai as genai

gmaps = googlemaps.Client(key=GOOGLE_API_KEY)
genai.configure(api_key=GOOGLE_AI_KEY)

# Create your views here.


def index(request):
    return render(request, "find/index.html")

@login_required
def find(request):
    if request.method == "POST":

        latitude = request.POST.get("latitude")
        longitude = request.POST.get("longitude")
        url = "https://places.googleapis.com/v1/places:searchNearby"
        myHeader = {
            'Content-Type': 'application/json',
            'X-Goog-Api-Key': GOOGLE_API_KEY,
            'X-Goog-FieldMask': 'places.displayName,places.id,places.types,places.formattedAddress'
        }
        myBody = {
            'includedTypes': ['restaurant'],
            'maxResultCount': 10,
            'locationRestriction': {
                'circle': {
                    'center': {
                        'latitude': latitude,
                        'longitude': longitude,
                    },
                    'radius': 2000.0
                }
            },
            'rankPreference': 'DISTANCE'
        }

        result = requests.post(url, json=myBody, headers=myHeader).json()
        # print(type(result)) // DICTIONARY
        # print(result)
        places = []
        for restaurant in result['places']:
            new_data = {
                'displayName': restaurant['displayName']['text'],
                'address': restaurant['formattedAddress'],
                'types':  restaurant['types'],
            }
            places.append(new_data)
            
            # print(f"Name: {restaurant['displayName']['text']}")
            # print(f"Address: {restaurant['formattedAddress']}")
            # print(f"Types: {restaurant['types']}")
            # print("-" * 20)

        context = {
            "latitude": latitude,
            "longitude": longitude,
            "places": places,
        }
        return render(request, "find/find.html", context)
        # nearby_restaurants = gmaps.places_nearby(
        #     location=(latitude, longitude),
        #     radius = 5000,
        #     type = 'restaurant',
        #     rankby = 'distance',
        # )
        # print(nearby_restaurants)
        # nearby_restaurants = gmaps.places.textsearch(
        #     query='restaurants',  # Search for restaurants (can be more specific)
        #     location=(latitude, longitude),  # Your location
        #     radius=5000,  # Search within a 5 km radius
        #     rankby='distance',  # Sort by distance
        # )
        # for restaurant in nearby_restaurants['results']:
        #     print(f"Name: {restaurant['name']}")
        #     print(f"Address: {restaurant['vicinity']}")
        #     print(f"Types: {restaurant['types']}")
        #     print("-" * 20)
    else:
        return redirect('index')
    
@login_required
def generate(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        response = generate_recommendation(data)
        return JsonResponse({'response': md_to_html(response)}, safe=False)
    else:
        return JsonResponse({'message': 'Invalid request Method'}, status=400)

@login_required
def recipe(request):
    try:
        profile = Profile.objects.get(user=request.user)
        return render(request, 'find/recipe.html')
    except Profile.DoesNotExist:
        return redirect('users:createProfile')

@login_required
def generateRecipe(request):
    if request.method == 'POST':
        profile = Profile.objects.get(user=request.user)
        data = json.loads(request.body)
        item = data['item']
        response = json.loads(generate_recipe(item, profile))
        # response['steps'] = md_to_html(response['steps'])
        return JsonResponse({"response": response})
    else:
        return JsonResponse({"message": "Invalid request method"}, status=400)
    

@login_required
def findIngredient(request):
    try:
        profile = Profile.objects.get(user=request.user)
        return render(request, "find/ingredients.html")
    except Profile.DoesNotExist:
        return redirect('users:createProfile')

@login_required
def ingredientRecipe(request):
    if request.method == 'POST':
        profile = Profile.objects.get(user=request.user)
        data = json.loads(request.body)
        ingredients = data['ingredients']
        response = json.loads(generate_ingredient_recipe(ingredients, profile))
        # response['steps'] = md_to_html(response['steps'])
        
        return JsonResponse({"response": response}, safe=False)
    else:
        return JsonResponse({"message": "Invalid request method"}, status=400)

find/templates/find/base.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Food App</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-indigo-300 text-white">
    <header class="bg-indigo-700 text-white sticky top-0 z-10">
        <section class="max-w-4xl mx-auto p-4 flex justify-between items-center ">
            <a href="{% url 'index' %}">
                <h1 class="text-3xl font-medium">
                    🍔 Food Sense
                </h1>
            </a>
            <div>
                <nav class="block space-x-8 text-xl" aira-label="main">
                    {% if not user.is_authenticated %}
                    <a href="{% provider_login_url 'google' %}" class="hover:opacity-90">Sign In with Google</a>
                    {% else %}
                    <a href="#" class="hover:opacity-90">Profile</a>
                    <a href="{% url 'account_logout' %}">Sign Out</a>
                    {% endif %}
                    
                </nav>
            </div>
        </section>
    </header>
    {% block body %}
    {% endblock %}
</body>
<script>
    {% block script %}
    {% endblock %}
</script>
</html>

find/templates/find/find.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto px-4 py-8">
    <div class="flex flex-col md:flex-row gap-8">
        <div class="w-full md:w-1/2">
            {% for restaurant in places %}
            <div class="m-5 rounded-lg bg-white px-6 py-8 shadow-2xl ring-1 ring-slate-900">
                <h1 class="text-base font-medium tracking-tight text-slate-900">{{ restaurant.displayName }}</h1>
                <h2 class="mt-2 text-sm text-slate-600">{{ restaurant.address }}</h2>
                <div id="types">
                    <ul class="text-black">
                        {% for type in restaurant.types %}
                        <li>{{ type }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="w-full md:w-1/2">
            <h2 class="text-2xl font-bold mb-4">AI Recommendation:</h2>
            <div id="aiResponse" class="border rounded-md p-4">
                Loading AI response...
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

async function getAIresponse(){
    const endpointUrl = '/generate/';
    const places = {{places|safe}}
    console.log(places)
    const payload = {
        'places': places,
        'thing': 'hello',
    };
    try {
        const response = await fetch(endpointUrl, {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify(payload),
        });
        if (response.ok) {
            const data = await response.json();
            console.log(data);
            console.log({{ data.response | markdown | safe }}) <!-- This is what I tried.-->
            document.getElementById("aiResponse").innerHTML = data.response
        } else {
            console.error("error");
        }
    } catch (error) {
        console.error("Error occured");
    }
}
window.onload = async() => {
    console.log("hello")
    {% comment %} document.getElementById('loading').style.display = 'block'; {% endcomment %}
    await getAIresponse();
}
{% endblock %}

find/templates/find/index.html
{% extends 'base.html' %}
{% block body %}
    <form id="locationForm" method="POST" action="find/">
        {% csrf_token %}
        <input type="hidden" name="latitude" id="latitudeInput">
        <input type="hidden" name="longitude" id="longitudeInput">
    </form>

    <section id="intro" class="flex flex-row md:flex-col justify-center p-6 items-center mb-12">
        <h2 class="max-w-4xl text-4xl font-bold text-left md:text-center ">
            Modern <span id="point" class="text-[#e28413]">Food Recommender</span>
        </h2>
        <p class="max-w-md text-2xl mt-4 text-left md:text-center">Smart food recommender that improves your lifestyle</p>
    </section>

<div class="flex flex-col justify-center items-center space-y-2">
            <button id="getLocationButton" onclick="getLocation()" class="bg-[#e28413] hover:bg-[#e28413] text-white font-bold py-2 px-4 rounded-full transition transform ease-in-out duration-300 hover:scale-105 opacity-100 hover:opacity-100 disabled:opacity-50">Nearby Search</button>
        <button id="getRecipeButton" onclick="getRecipe()" class="bg-[#e28413] hover:bg-[#e28413] text-white font-bold py-2 px-4 rounded-full transition transform ease-in-out duration-300 hover:scale-105 opacity-100 hover:opacity-100 disabled:opacity-50">Get Recipe</button>
        <button id="getIngredients" onclick="getIngredients()" class="bg-[#e28413] hover:bg-[#e28413] text-white font-bold py-2 px-4 rounded-full transition transform ease-in-out duration-300 hover:scale-105 opacity-100 hover:opacity-100 disabled:opacity-50">Ingredients</button>
        <!--
        <a href="#" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full transition transform ease-in-out duration-300 hover:scale-105">Planner</a>
        -->
    </div>
    
    <div style="display: none;" id="loading-circle" class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"> 
        <svg width="48" height="48" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_nOfF{animation:spinner_qtyZ 2s cubic-bezier(0.36,.6,.31,1) infinite}.spinner_fVhf{animation-delay:-.5s}.spinner_piVe{animation-delay:-1s}.spinner_MSNs{animation-delay:-1.5s}@keyframes spinner_qtyZ{0%{r:0}25%{r:3px;cx:4px}50%{r:3px;cx:12px}75%{r:3px;cx:20px}100%{r:0;cx:20px}}</style><circle class="spinner_nOfF" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_fVhf" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_piVe" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_MSNs" cx="4" cy="12" r="3"/></svg>
    </div>
{% endblock %}
{% block script %}
<script>
    const getLocationButton = document.getElementById("getLocationButton")
    const getRecipeButton = document.getElementById("getRecipeButton")
    const getIngredientsButton = document.getElementById("getIngredients")
    const loadingCircle = document.getElementById("loading-circle")
    let isLoading = false; 

    function handleLoadingState() {
        if (isLoading) {
            getLocationButton.disabled = true;
            getRecipeButton.disabled = true;
            getIngredientsButton.disabled = true;
            loadingCircle.style.display = 'block';
        } else {
            getLocationButton.disabled = false;
            getRecipeButton.disabled = false;
            getIngredientsButton.disabled = false;
            loadingCircle.style.display = 'none';
        }
    }

    async function getLocation() {
        isLoading = true; 
        handleLoadingState(); // Update loading state

        if (navigator.geolocation) {
            await navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            alert("Location is not allowed by this browser.")
        }
    }
    async function getRecipe() {
        isLoading = true; 
        handleLoadingState(); // Update loading state
        window.location.href = "{% url 'recipe' %}"
    }

    async function getIngredients() {
        isLoading = true; 
        handleLoadingState(); // Update loading state
        window.location.href = "{% url 'ingredient' %}"
    }
    async function showPosition(position) {
        const lat = position.coords.latitude;
        const long = position.coords.longitude;
    
        document.getElementById('latitudeInput').value = lat;
        document.getElementById('longitudeInput').value = long;
    
        document.getElementById('locationForm').submit();
        handleLoadingState(); // Update loading state
    }
    onpageshow = async() => {
        getLocationButton.disabled = false;
        getRecipeButton.disabled = false;
        getIngredientsButton.disabled = false;
        loadingCircle.style.display = 'none';
    }

</script>
{% endblock %}

find/templates/find/ingredients.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto p-4">
    <h1 class="text-4xl font-bold text-center mb-8 text-[#000022]">Find Recipes by Ingredients</h1>
    <p class="text-gray-600 text-lg mb-4 text-center">Enter your ingredients, and let our AI find delicious recipes using what you have on hand!</p>

    <div class="mb-4">
        <div class="flex items-center">
            <input type="text" id="new-ingredient" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mr-2" placeholder="Enter an ingredient">
            <button id="addIngredient" onclick="addIngredient()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Add</button>
        </div>
    </div>

    <div class="flex flex-col items-center mt-4"> 
        <ul id="ingredient-list" class="list-disc list-inside">
            <!-- Added Ingredients will be added here -->
        </ul>
    </div>

    <div class="flex justify-center mt-4"> 
        <button id="submitIngredients" onclick="submitIngredients()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Submit</button>
    </div>

    <div style="display: none;" id="loading-circle" class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"> 
        <svg width="48" height="48" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_nOfF{animation:spinner_qtyZ 2s cubic-bezier(0.36,.6,.31,1) infinite}.spinner_fVhf{animation-delay:-.5s}.spinner_piVe{animation-delay:-1s}.spinner_MSNs{animation-delay:-1.5s}@keyframes spinner_qtyZ{0%{r:0}25%{r:3px;cx:4px}50%{r:3px;cx:12px}75%{r:3px;cx:20px}100%{r:0;cx:20px}}</style><circle class="spinner_nOfF" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_fVhf" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_piVe" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_MSNs" cx="4" cy="12" r="3"/></svg>
    </div>

    <div id="recipe-container" class="mt-4 bg-gray-100 rounded-lg p-4 shadow-md" style="display:none;">
        <h2 id="title" class="text-2xl font-bold mb-4 text-[#000022]"></h2>

        <p id="description" class="text-gray-700 mb-4"></p>
        <div class="mb-4">
            <h3 class="text-lg font-bold mb-2 text-[#000022]">Ingredients:</h3>
            <ul id="ingredients-list" class="list-disc list-inside text-[#000022]">
            </ul>
        </div>

        <div class="mb-4">
            <h3 class="text-lg font-bold mb-2 text-[#000022]">Steps:</h3>
            <div id="result" class="prose prose-lg text-[#000022]"></div>
        </div>

        <button id="saveRecipeBtn" onclick="saveRecipe()" class="bg-green-500 hover:bg-green-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save Recipe</button>
    </div>

</div>
{% endblock body %}
{% block script %}
<script>
    const ingredientInput = document.getElementById("new-ingredient");
    const ingredientList = document.getElementById("ingredient-list");
    const resultDiv = document.getElementById("result");
    const recipeContainer = document.getElementById("recipe-container");
    const titleDiv = document.getElementById("title");
    const ingredientsList = document.getElementById("ingredients-list");
    const saveRecipeBtn = document.getElementById("saveRecipeBtn");
    const loading = document.getElementById("loading-circle")
    const submitIngredientsBtn = document.getElementById("submitIngredients")
    const descriptionDiv = document.getElementById("description")

    let allIngredients = [];

    function addIngredient() {
        const newIngredient = ingredientInput.value.trim();
        if (newIngredient !== "") {
            const listItem = document.createElement("li");
            listItem.setAttribute("id", `tag-${newIngredient}`);
            listItem.innerHTML = `
                <span class="mr-2">${newIngredient}</span>
                <button onclick="deleteTag('${newIngredient}')" class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded transition duration-300 ml-auto hover:opacity-90"> 
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
            `;
            ingredientList.appendChild(listItem);
            ingredientInput.value = "";
            allIngredients.push(newIngredient);
        }
    }

    function deleteTag(tagId) {
        const listItem = document.getElementById(`tag-${tagId}`);
        if (listItem) {
            listItem.remove();
            // Remove the ingredient from the array
            allIngredients = allIngredients.filter(item => item !== tagId);
        }
    }

    function submitIngredients() {
        if (allIngredients.length > 0) {
            const endpointURL = "{% url 'ingredientRecipe' %}";
            const payload = {
                "ingredients": allIngredients
            };
            loading.style.display = 'block';
            recipeContainer.style.display = "none";
            submitIngredientsBtn.disabled = true;
            // Send POST data with the list, and console.log the response. 
            fetch(endpointURL, {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify(payload)
            })
            .then(response => response.json())
            .then(data => {
                console.log(data); 
                recipeContainer.style.display = "block";
                titleDiv.textContent = data.response.name;

                // Clear previous ingredients
                ingredientsList.innerHTML = ''; 
                descriptionDiv.innerHTML = data.response.description;
                data.response.ingredients.forEach(ingredient => {
                    const li = document.createElement("li");
                    li.textContent = ingredient;
                    ingredientsList.appendChild(li);
                });
                resultDiv.innerHTML = data.response.steps;
            })
            .catch(error => {
                console.error("Error submitting ingredients:", error);
            })
            .finally(() => { 
                loading.style.display = 'none';
                submitIngredientsBtn.disabled = false;
            });
        }
    }

    async function saveRecipe() {
        const endpointURL = '{% url "users:save_favorite" %}'
        try {
            const response = await fetch(endpointURL, {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({'item': document.getElementById("title").innerHTML, 'ingredients': document.getElementById('ingredients-list').innerHTML,'steps': document.getElementById("result").innerHTML})
            });

            if (response.ok) {
                console.log("Recipe saved to favorites!");
                alert("Recipe saved to favorites!");
                saveRecipeBtn.disabled = true;
                // You might want to add some feedback to the user here (e.g., a message)
            } else {
                console.error("Error saving recipe:", response.status);
            }
        } catch (error) {
            console.error("Error occurred:", error);
        }
    }
    document.getElementById("new-ingredient").addEventListener("keypress", function(event) {
        if (event.key === "Enter") {
            addIngredient();
        }
    });
</script>
{% endblock script %}

find/templates/find/recipe.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto p-4">
    <h1 class="text-4xl font-bold text-center mb-8 text-[#000022]">Find any recipe you want!</h1>
    <p class="text-gray-600 text-lg mb-4 text-center">Tell us what you're looking for! The more details you provide, the better our recommendations will be.</p>
    <div class="flex items-center mb-8">
        <input type="text" id="recipeInput" placeholder="Type any recipe..." class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        <button id="sendRecipeButton" onclick="sendRecipe()" class="bg-[#e28413] hover:bg-[#bc7d30] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline ml-2">Send</button>
    </div>
    <div style="display: none;" id="loading-circle" class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"> 
        <svg width="96" height="96" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_nOfF{animation:spinner_qtyZ 2s cubic-bezier(0.36,.6,.31,1) infinite}.spinner_fVhf{animation-delay:-.5s}.spinner_piVe{animation-delay:-1s}.spinner_MSNs{animation-delay:-1.5s}@keyframes spinner_qtyZ{0%{r:0}25%{r:3px;cx:4px}50%{r:3px;cx:12px}75%{r:3px;cx:20px}100%{r:0;cx:20px}}</style><circle class="spinner_nOfF" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_fVhf" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_piVe" cx="4" cy="12" r="3"/><circle class="spinner_nOfF spinner_MSNs" cx="4" cy="12" r="3"/></svg>
    </div>

    <div id="recipe-container" class="mt-4 bg-gray-100 rounded-lg p-4 shadow-md" style="display:none;">
        <h2 id="title" class="text-2xl font-bold mb-4 text-[#000022]"></h2>


        <p id="description" class="text-gray-700 mb-4"></p>

        <div class="mb-4">
            <h3 class="text-lg font-bold mb-2 text-[#000022]">Ingredients:</h3>
            <ul id="ingredients-list" class="list-disc list-inside text-[#000022]">
            </ul>
        </div>

        <div class="mb-4">
            <h3 class="text-lg font-bold mb-2 text-[#000022]">Steps:</h3>
            <div id="result" class="prose prose-lg text-[#000022]"></div>
        </div>

        <button id="saveRecipeBtn" onclick="saveRecipe()" class="bg-green-500 hover:bg-green-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save Recipe</button>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
    const recipeInput = document.getElementById("recipeInput")
    const resultDiv = document.getElementById("result");
    const recipeContainer = document.getElementById("recipe-container");
    const titleDiv = document.getElementById("title");
    const ingredientsList = document.getElementById("ingredients-list");
    const saveRecipeBtn = document.getElementById("saveRecipeBtn");
    const descriptionDiv = document.getElementById("description")

    async function sendRecipe(){
        const message = recipeInput.value.trim();
        if (message === "") {
            return;
        }
        food = message
        recipeInput.value = ""
        document.getElementById("loading-circle").style.display = 'block';
        recipeContainer.style.display = "none";
        const endpointURL = '{% url "generateRecipe" %}'
        try {
            const response = await fetch(endpointURL, {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({'item': message})
            });

            if (response.ok) {
                const data = await response.json();
                console.log(data);

                document.getElementById("loading-circle").style.display = 'none';
                recipeContainer.style.display = "block";
                titleDiv.textContent = data.response.name;

                // Clear previous ingredients
                ingredientsList.innerHTML = ''; 

                descriptionDiv.innerHTML = data.response.description;

                data.response.ingredients.forEach(ingredient => {
                    const li = document.createElement("li");
                    li.textContent = ingredient;
                    ingredientsList.appendChild(li);
                });
                resultDiv.innerHTML = data.response.steps;
            } else {
                console.error("Error sending message:", response.status);
            }
        } catch (error) {
            console.error("Error occurred:", error);
        } 

    }
    async function saveRecipe() {
        const endpointURL = '{% url "users:save_favorite" %}'
        try {
            const response = await fetch(endpointURL, {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({'item': document.getElementById("title").innerHTML, 'ingredients': document.getElementById('ingredients-list').innerHTML,'steps': document.getElementById("result").innerHTML})
            });

            if (response.ok) {
                console.log("Recipe saved to favorites!");
                alert("Recipe saved to favorites!");
                saveRecipeBtn.disabled = true

                // You might want to add some feedback to the user here (e.g., a message)
            } else {
                console.error("Error saving recipe:", response.status);
            }
        } catch (error) {
            console.error("Error occurred:", error);
        }
    }
</script>
{% endblock script %}

find/templates/find/text.html
{% extends 'base.html' %}
{% block body %}
<div class="container mx-auto px-4 py-8">
    <div class="flex flex-col md:flex-row gap-8">
        <div class="w-full md:w-1/2">
            <h2 class="text-2xl font-bold mb-4 text-[#000022]">Nearby Restaurants:</h2>
            <div class="bg-gray-100 rounded-lg p-4 shadow-md overflow-y-auto max-h-96">
                <ul class="list-disc list-inside">
                    {% for restaurant in places %}
                        <li class="mb-4">
                            <h3 class="text-lg font-medium text-[#000022]">{{ restaurant.displayName }}</h3>
                            <p class="text-gray-700">{{ restaurant.address }}</p>
                            <ul class="text-gray-700 list-disc list-inside">
                                {% for type in restaurant.types %}
                                    <li>{{ type }}</li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="w-full md:w-1/2">
            <h2 class="text-2xl font-bold mb-4 text-[#000022]">AI Recommendation:</h2>
            <div id="aiResponse" class="border rounded-md p-4 bg-gray-100">
                Loading AI response...
            </div>
        </div>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>
async function getAIresponse(){
    const endpointUrl = '/generate/';
    const places = {{places|safe}}
    console.log(places)
    const payload = {
        'places': places,
        'thing': 'hello',
    };
    try {
        const response = await fetch(endpointUrl, {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify(payload),
        });
        if (response.ok) {
            const data = await response.json();
            document.getElementById("aiResponse").innerHTML = data.response
        } else {
            console.error("error");
        }
    } catch (error) {
        console.error("Error occured");
    }
}
window.onload = async() => {
    console.log("hello")
    {% comment %} document.getElementById('loading').style.display = 'block'; {% endcomment %}
    await getAIresponse();
}
</script>
{% endblock script %}